on:
  push:
    branches:
    - main

jobs:
  container_build:
    name: tado_aa container build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Docker Login
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.commit.outputs.short }}
          
